name: my_music
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # STATE MANAGEMENT
  provider: ^6.0.0
  rxdart: ^0.27.1
  injector: ^2.0.0
  
  # AUDIO
  just_audio: ^0.7.4+1
  audio_service: ^0.18.1
  audio_session: ^0.1.0
  on_audio_query: ^2.2.0
  on_audio_room: ^2.0.0
  equalizer:
    git:
      url: https://github.com/TcBello/equalizer.git
  
  # UTIL
  device_info: ^2.0.2
  uuid: ^3.0.4
  auto_size_text: 3.0.0-nullsafety.0
  fluttertoast: ^8.0.8
  simple_animations: ^3.1.1
  supercharged: ^2.0.0
  marquee_text: ^2.0.0
  image_picker: ^0.7.4
  # flutter_colorpicker: ^0.4.0
  flutter_colorpicker: ^1.0.3
  palette_generator: ^0.3.0

  # UI
  animated_text_kit: ^4.2.1
  theme_provider: ^0.5.0
  path_provider: ^2.0.1
  miniplayer:
    git:
      url: https://github.com/TcBello/miniplayer.git
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master
  flutter_inner_drawer:
    git:
      url: https://github.com/TcBello/flutter_inner_drawer.git
  audio_video_progress_bar: ^0.9.0
  draggable_scrollbar: ^0.1.0


  # DATABASE
  shared_preferences: ^2.0.5

  # SHARE AND FEEDBACK
  url_launcher: ^6.0.9
  rate_my_app: ^1.1.1
  share_plus: ^2.1.4

  # ADVERTISEMENT
  native_admob_flutter: ^1.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
          weight: 700

    - family: HK Grotesk
      fonts:
        - asset: assets/fonts/HK Grotesk/HKGrotesk-Light.otf
          weight: 300
        - asset: assets/fonts/HK Grotesk/HKGrotesk-Regular.otf
          weight: 400
        - asset: assets/fonts/HK Grotesk/HKGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/HK Grotesk/HKGrotesk-SemiBold.otf
          weight: 600
        - asset: assets/fonts/HK Grotesk/HKGrotesk-Bold.otf
          weight: 700
        - asset: assets/fonts/HK Grotesk/HKGrotesk-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/HK Grotesk/HKGrotesk-Black.otf
          weight: 900
    
    - family: Chivo
      fonts:
        - asset: assets/fonts/Chivo/Chivo-Thin.otf
          weight: 100
        - asset: assets/fonts/Chivo/Chivo-Light.otf
          weight: 300
        - asset: assets/fonts/Chivo/Chivo-Regular.otf
          weight: 400
        - asset: assets/fonts/Chivo/Chivo-Medium.otf
          weight: 500
        - asset: assets/fonts/Chivo/Chivo-Bold.otf
          weight: 700
        - asset: assets/fonts/Chivo/Chivo-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Chivo/Chivo-Black.otf
          weight: 900
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
